server {
    server_name melvinsam.duckdns.org;

    # ROOT
    location / {
        default_type application/json;
        return 200 '{"status":"success"}';
    }

    # HEALTH (FINAL FIX)
    location /health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    # ME (FIX NAME FORMAT)
    location /me {
        default_type application/json;
        return 200 '{"name":"UgwuSamuelEbube","email":"melvinsamuel070@gmail.com","github":"https://github.com/melvinsamuel070"}';
    }

    # API (DO NOT TOUCH)
    location /api {
        default_type application/json;
        return 200 '{"message":"HNGI14 Stage 0","track":"DevOps","username":"UgwuSamuelEbube"}';
    }

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/melvinsam.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/melvinsam.duckdns.org/privkey.pem;
}
